export const NATIVE_GREETINGS: Record<string, string> = {
  am: "ሰላም",
  ar: "مرحبا",
  bn: "নমস্কার",
  cs: "Ahoj",
  da: "Hej",
  de: "Hallo",
  el: "Γειά σου",
  es: "¡Hola!",
  fa: "سلام",
  fi: "Hei",
  fr: "Bonjour",
  he: "Shalom",
  hi: "नमस्ते",
  hu: "Szia",
  hy: "Բարև",
  id: "Halo",
  it: "Ciao",
  ja: "こんにちは",
  ka: "გამარჯობა",
  ko: "안녕하세요",
  ms: "Selamat",
  nl: "Hallo",
  no: "Hei",
  pl: "Cześć",
  pt: "Olá",
  ro: "Bună",
  ru: "Здравствуйте",
  sk: "Ahoj",
  sv: "Hallå",
  sw: "Jambo",
  th: "สวัสดี",
  tl: "Kamusta",
  tr: "Merhaba",
  uk: "Вітаю",
  ur: "سلام",
  vi: "Xin chào",
  zh: "你好",
  zu: "Sawubona",
};

export function getNativeGreeting(langCode: string): string | null {
  const base = langCode.toLowerCase().split("-")[0];
  return NATIVE_GREETINGS[base] || null;
}
